Beta v5
appujet/lavamusic pull request #723
Opened 2024-09-15 01:27 UTC by hwangsihu

2024-09-15 13:32 UTC, LucasB25 commented
update pr

2024-09-15 14:18 UTC, hwangsihu commented
What do you mean

2024-09-15 16:20 UTC, LucasB25 commented
![image](https://github.com/user-attachments/assets/751da7b7-2d69-4e3e-be55-3ecc74471d36)

2024-09-16 00:18 UTC, appujet requested changes
Don't need to change to BETA 

Beta will be Marge in few days

2024-09-16 00:19 UTC, appujet requested changes
Why you removed ?

2024-09-16 00:25 UTC, hwangsihu commented
Oh no, I was trying to run two bots to differentiate them, but I accidentally pushed it to that one. I'll run it back after I update the translation.
As for removing the command, as I said in the commit description, I don't know if it's due to the influence of lavalink-client, but I don't think it's necessary because it seems like the pitch and speed are saved. We can just make the pitch and speed the same.

2024-09-16 04:27 UTC, hwangsihu commented
Okay, I added it again. It's definitely annoying without it LOL

2024-09-16 18:19 UTC, appujet requested changes

2024-09-16 18:19 UTC, appujet commented on src/commands/filters/Rate.ts
Re add command

2024-09-16 18:20 UTC, appujet requested changes
Why did you enable Spotify, Apple Music, and other sources but set them to `false` by default in the `application.yml`?

2024-09-17 03:41 UTC, LucasB25 commented
Why would you want to add the lyrics plugin which does exactly the same thing as lavasrc lyrics?

2024-09-17 03:48 UTC, hwangsihu commented
The developer on Discord asked me to install that plugin, otherwise you could uninstall it yourself, I can't get it to work right now.

2024-09-17 03:50 UTC, hwangsihu commented
https://discord.com/channels/1082302532421943407/1082302533332115539/1285126518825029673

2024-09-17 04:56 UTC, infnibor commented
> https://discord.com/channels/1082302532421943407/1082302533332115539/1285126518825029673

"LavaSrc has support for said plugins
But it does not ship them
You need to install them by yourself if you want these features"

Read this again, just like lava-search are supported but you have to import the plugin from somewhere, the operation of which you set in lavasrc etc. The fact that you set the lyrics sources to on in lavasrc will only throw errors, because lavasrc will not find the necessary data / variables, which will be added by adding the lavalyrics plugin

2024-09-17 07:01 UTC, LucasB25 commented
> > https://discord.com/channels/1082302532421943407/1082302533332115539/1285126518825029673
> 
> "LavaSrc has support for said plugins But it does not ship them You need to install them by yourself if you want these features"
> 
> Read this again, just like lava-search are supported but you have to import the plugin from somewhere, the operation of which you set in lavasrc etc. The fact that you set the lyrics sources to on in lavasrc will only throw errors, because lavasrc will not find the necessary data / variables, which will be added by adding the lavalyrics plugin

https://discord.com/channels/1082302532421943407/1082302533332115539/1285492495735848990

2024-09-17 07:27 UTC, hwangsihu commented
```
npm start

> lavamusic@5.0.0-beta start
> npm run clean && node .


> lavamusic@5.0.0-beta clean
> node scripts/clean.js && npm run build


> lavamusic@5.0.0-beta build
> tsc --project tsconfig.json

src/utils/functions/player.ts:94:9 - error TS2367: This comparison appears to be unintentional because the types '"soundcloud" | "deezer" | "bandcamp" | "twitch" | "applemusic" | "yandexmusic" | "flowery-tts"' and '"jiosaavn"' have no overlap.

94     if (lastTrack.info.sourceName === "jiosaavn") {
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/utils/functions/player.ts:94
```
Hm

2024-09-17 09:07 UTC, appujet commented on src/utils/functions/player.ts
> -    if (lastTrack.info.sourceName === "jiosaavn") {
What version are you using in lavalink client ?

2024-09-17 09:08 UTC, appujet commented on src/utils/functions/player.ts
> -    if (lastTrack.info.sourceName === "jiosaavn") {
There doesn't need to do `any type`

2024-09-17 09:09 UTC, appujet approved these changes

2024-09-17 09:26 UTC, hwangsihu commented
But how do you fix player lag? It was fine in V4.

2024-09-17 09:28 UTC, hwangsihu commented
> What version are you using in lavalink client ?

Check out my package.json, I'm using 2.3.6, but not work, so I fixed it.

2024-09-18 06:56 UTC, LucasB25 commented
Please recreate a new PR because I made changes to your PR that you overwrote without having retrieved them before...

2024-09-18 08:28 UTC, appujet commented on src/utils/functions/player.ts
> -    if (lastTrack.info.sourceName === "jiosaavn") {
Please revert this commit

2024-09-18 08:31 UTC, closed without merging